### ISSUE TITLE
iPhone Contreoller Error

### ISSUE THREAD

**Issue by unseenmagik** [versx/iPhoneController#21]
Fresh clean install, iPhoneController runs but upon missing any command I get an error

```[2021-05-01 19:37:43 -04:00] [iPhoneController] [Error] Magik tried executing 'screen' but it errored: System.ComponentModel.Win32Exception: No such file or directory
[iPhoneController] Magik tried executing 'screen' but it errored: System.ComponentModel.Win32Exception: No such file or directory: Magik tried executing 'screen' but it errored: System.ComponentModel.Win32Exception: No such file or directory
7:37 PM [ERROR] [BOT] User Magik tried executing command screen and unknown error occurred.
: System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at iPhoneController.Utils.Shell.Execute(String cmd, String args, Int32& exitCode, Boolean includeErrorOutput) in /Users/pokemon/iPhoneController2/src/Utils/Shell.cs:line 50
   at iPhoneController.Models.Device.GetDevicesCfgUtil() in /Users/pokemon/iPhoneController2/src/Models/Device.cs:line 240
   at iPhoneController.Models.Device.GetAll() in /Users/pokemon/iPhoneController2/src/Models/Device.cs:line 102
   at iPhoneController.Commands.PhoneControl.ScreenshotAsync(CommandContext ctx, String phoneNames) in /Users/pokemon/iPhoneController2/src/Commands/PhoneControl.cs:line 100
   at DSharpPlus.CommandsNext.Command.ExecuteAsync(CommandContext ctx)```

**Comment by unseenmagik** [comment]
Fixed by installing AC2 command line tools
